services:
  _defaults:
    autowire: true
    autoconfigure: true

  StudioMitte\Riddle\:
    resource: '../Classes/*'

  StudioMitte\Riddle\Backend\EventListener\BackendPreviewEventListener:
    tags:
      - name: event.listener
        identifier: 'riddle/riddle'